name: CI

on: push

jobs:

  test:

    name: Lint
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install pylint mypy types-requests
      env:
        PIP_PROGRESS_BAR: off

    - name: Install package
      run: make install

    - name: Lint
      run: make lint

    - name: Typecheck
      run: make typecheck

    - name: Run
      run: dependency-graphql $REPO
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}

  publish:

    name: Publish
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install pypa/build
      run: pip install build
      env:
        PIP_PROGRESS_BAR: off

    - name: Build distribution
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dependency_graphql
        path: dist/

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        repository_url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        print_hash: true

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        print_hash: true

    - name: Clean up
      run: make clean
